/********************************************************************
* BBNormAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BBNormAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBBNormAnaDict();
extern void G__cpp_setup_inheritanceBBNormAnaDict();
extern void G__cpp_setup_typetableBBNormAnaDict();
extern void G__cpp_setup_memvarBBNormAnaDict();
extern void G__cpp_setup_globalBBNormAnaDict();
extern void G__cpp_setup_memfuncBBNormAnaDict();
extern void G__cpp_setup_funcBBNormAnaDict();
extern void G__set_cpp_environmentBBNormAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BBNormAna.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BBNormAnaDictLN_TClass;
extern G__linked_taginfo G__BBNormAnaDictLN_TBuffer;
extern G__linked_taginfo G__BBNormAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__BBNormAnaDictLN_TObject;
extern G__linked_taginfo G__BBNormAnaDictLN_TNamed;
extern G__linked_taginfo G__BBNormAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BBNormAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BBNormAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BBNormAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BBNormAnaDictLN_THaRunBase;
extern G__linked_taginfo G__BBNormAnaDictLN_TDatime;
extern G__linked_taginfo G__BBNormAnaDictLN_THaEvData;
extern G__linked_taginfo G__BBNormAnaDictLN_THaAnalysisObject;
extern G__linked_taginfo G__BBNormAnaDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__BBNormAnaDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__BBNormAnaDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__BBNormAnaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BBNormAnaDictLN_THaPhysicsModule;
extern G__linked_taginfo G__BBNormAnaDictLN_TBits;
extern G__linked_taginfo G__BBNormAnaDictLN_THaScaler;
extern G__linked_taginfo G__BBNormAnaDictLN_THaADCHelicity;
extern G__linked_taginfo G__BBNormAnaDictLN_BNormData;
extern G__linked_taginfo G__BBNormAnaDictLN_BBNormAna;
extern G__linked_taginfo G__BBNormAnaDictLN_vectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgR;
extern G__linked_taginfo G__BBNormAnaDictLN_reverse_iteratorlEvectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BBNormAnaDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__BBNormAnaDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
