/********************************************************************
* NormAna_RDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NormAna_RDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNormAna_RDict();
extern void G__cpp_setup_inheritanceNormAna_RDict();
extern void G__cpp_setup_typetableNormAna_RDict();
extern void G__cpp_setup_memvarNormAna_RDict();
extern void G__cpp_setup_globalNormAna_RDict();
extern void G__cpp_setup_memfuncNormAna_RDict();
extern void G__cpp_setup_funcNormAna_RDict();
extern void G__set_cpp_environmentNormAna_RDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NormAna_R.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NormAna_RDictLN_TClass;
extern G__linked_taginfo G__NormAna_RDictLN_TBuffer;
extern G__linked_taginfo G__NormAna_RDictLN_TMemberInspector;
extern G__linked_taginfo G__NormAna_RDictLN_TObject;
extern G__linked_taginfo G__NormAna_RDictLN_TNamed;
extern G__linked_taginfo G__NormAna_RDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NormAna_RDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAna_RDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NormAna_RDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAna_RDictLN_THaRunBase;
extern G__linked_taginfo G__NormAna_RDictLN_TDatime;
extern G__linked_taginfo G__NormAna_RDictLN_THaEvData;
extern G__linked_taginfo G__NormAna_RDictLN_THaAnalysisObject;
extern G__linked_taginfo G__NormAna_RDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__NormAna_RDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__NormAna_RDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__NormAna_RDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAna_RDictLN_THaPhysicsModule;
extern G__linked_taginfo G__NormAna_RDictLN_TBits;
extern G__linked_taginfo G__NormAna_RDictLN_THaScaler;
extern G__linked_taginfo G__NormAna_RDictLN_THaADCHelicity;
extern G__linked_taginfo G__NormAna_RDictLN_BNormData;
extern G__linked_taginfo G__NormAna_RDictLN_NormAna_R;
extern G__linked_taginfo G__NormAna_RDictLN_vectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgR;
extern G__linked_taginfo G__NormAna_RDictLN_reverse_iteratorlEvectorlEBRocScalermUcOallocatorlEBRocScalermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NormAna_RDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__NormAna_RDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
