// ***************************************************
//
// This script will take an input file that contains 
// a run number, generated by batch_replay, and run it
// through replay_nohist_R.C.
//
// 2011-05-20
// Elena Long
//
// ***************************************************

#include <iostream>
#include <fstream>
#include <string>
#include <string.h>
#include <math.h>
#include <iomanip>
using namespace std;


void replay_script_R_nohist(){

	cout << "Running replay_script_R_nohist..." << endl;

	string line = "";
	ifstream runNumberInputFile ("./input.file");
	getline(runNumberInputFile, line);
	int inRunNumber = atoi(line.c_str());

	cout << "Run Number: " << inRunNumber << endl;

	TString toAnalyze = "replay_nohists_R(";
	toAnalyze += inRunNumber;
	toAnalyze += ",-1)";

	gROOT->ProcessLine(toAnalyze);

	gROOT->ProcessLine(".q");

}







































